services:
  # nlpui:
  #   build:
  #     context: ./src/app
  #   # To debug startup code, add --wait-for-client after "python -m debugpy" (see https://github.com/microsoft/debugpy)
  #   command: python -m debugpy --listen 0.0.0.0:5678 app.py
  #   ports:
  #     - 8080:80
  #     - 5678:5678
  #   environment:
  #     - JWT_KEY=fake_secret
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_HOST=pgvector
  #     - UVICORN_HOST=0.0.0.0 # TODO: Figure out how to only accept connections from local machine
  #   volumes:
  #     - ./src/app:/code/app
  #   depends_on:
  #     - pgvector
  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
